server:
    port: 0

spring:
    application:
        name: ProductService
    datasource:
      url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb
      username: root
      password: admin-password
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
      hibernate:
        ddl-auto: update
eureka:
    client:
      service-url:
          defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true
    instance:
      prefer-ip-address: true